version: 0.2

env:
  variables:
    FLASK_DB_URI: $FLASK_DB_URI
    FLASK_SECRET_KEY: $FLASK_SECRET_KEY

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - apt-get install -y python3-venv
      - python3.6 -m venv test_venv
      - . test_venv/bin/activate
      - pip install --upgrade pip
      - pip install .
      - pip install -r requirements.txt
  build:
    commands:
      - echo Prebuild complete
artifacts:
  files:
    - '**/*'