version: 0.2

env:
  variables:
    FLASK_DB_URI: $FLASK_DB_URI
    FLASK_SECRET_KEY: $FLASK_SECRET_KEY

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo Prebuild complete
artifacts:
  files:
    - '**/*'