version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
  pre_build:
    commands:
      - sudo apt install update -y
      - sudo apt-get install -y python3 python3-pip python3-venv
      - python3.6 -m venv test_venv
      - . test_venv/bin/activate
      - pip3 install --upgrade pip
      - pip3 install .
      - pip3 install -r requirements.txt
  build:
    commands:
      - echo Prebuild complete
artifacts:
  files:
    - '**/*'