version: 0.2

env:
  variables:
    FLASK_DB_URI: $FLASK_DB_URI
    FLASK_SECRET_KEY: $FLASK_SECRET_KEY

phases:
  install:
    runtime-versions:
      python: 3.8
  pre-build:
    commands:
      - apt-get install -y python3-venv python3-pip
      - python3 -m venv venv
      - . venv/bin/activate
      - pip install -r requirements.txt
artifacts:
  files:
    - '**/*'