version: 0.2

phases:
  install:
    commands:
      - echo Setting up virtualenv
      - python -m venv venv
      - . venv/bin/activate
      - echo Installing requirements from file
      - pip3 install -r requirements.txt
    
artifacts:
  files:
    - '**/*'
